#pragma config(Sensor, S1,     rightTracker,   sensorLightActive)
#pragma config(Sensor, S2,     leftTracker,    sensorColorNxtNONE)
#pragma config(Sensor, S3,     vision,         sensorSONAR)
#pragma config(Motor,  motorB,          mLeft,         tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          mRight,        tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define SPEED 100
#define ROTATION_SPEED  30
#define lightTreshold  50

const string calibrationFile = "lightRange.txt";
TFileIOResult nIoResult;
TFileHandle hFileHandle;
int nFileSize = 20;
long tLowLight = 600;
long tHighLight = 400;

float getLightPortion() {
	float result;
	long numerator, denominator;
	numerator = (long) SensorRaw[rightTracker] - tLowLight;
	denominator = tHighLight - tLowLight;
	result = (float) numerator / denominator;
	if(result < 0) {result = 0;}
	if(result < 1) {result = 1;}
	return result;
}

float getLightPercent() {
	return 100*getLightPortion();
}

void initLightSensor() {
  SensorType[S1] = sensorLightActive;
 // CloseAllHandles(nIoResult);
 // OpenRead( hFileHandle, nIoResult, calibrationFile, nFileSize);
  //ReadLong(hFileHandle, nIoResult, tLowLight);
  //ReadLong(hFileHandle, nIoResult, tHighLight);
  //Close(hFileHandle, nIoResult);

}
void forward(int new_speed) {
	motor[mLeft] = new_speed;
	motor[mRight] = new_speed;
}

void left(int rotation_speed) {
	motor[mLeft] = rotation_speed;
	motor[mRight] = -rotation_speed;
}

void slow_stop(int speed) {
	int current_speed = speed;
	for(int i = speed; i > 0; i--) {
		forward(i);
		wait1Msec(10);
	}
}

void play_kut_sound() {
    PlayImmediateTone(random(10000), 5);
}

void right(int rotation_speed) {
	motor[mLeft] = -rotation_speed;
	motor[mRight] = rotation_speed;
}

void startRobot() {
	int stopped = 0;
	int running = 1;
	int value = SensorValue[rightTracker];
	while(running) {
		play_kut_sound();
		if(SensorValue(vision) < 25 && !stopped) {
			slow_stop(SPEED);
			running = 0;
		}
		else if(1) {
			left(SPEED);
		}
		else if(SensorValue(rightTracker) > 50 && SensorValue(rightTracker) < 40) {
		  right(SPEED);
		}
		else {
			forward(SPEED);
		}
	}
}

task main()
{
	initLightSensor();
	int constantPower = 45;
	int variablePower = 20;
	int intergralConstant = 8;
	int derivativeConstant = 15;
	float previousError = 0;
	float Kp = 0.0;
	float Ki = 0.0;
	float Kd = 0.0;
	nxtDisplayTextLine(0, "TEST: %d", getLightPercent());
	while(1) {
	    Kp = ((getLightPercent() - 50) / 50);
	    Ki = Ki + ((getLightPercent() - 50) / 50);
	    Kd = (Kp - previousError);
	    motor[mLeft] = constantPower + (Kp * variablePower) + (Ki * intergralConstant) + (Kd * derivativeConstant);
	    motor[mRight] = constantPower - (Kp * variablePower) - (Ki * intergralConstant) - (Kd * derivativeConstant);
	    previousError = Kp;
	}
}
